GET http://localhost:3000/vehiculos/find?marca=Acura

###

GET http://localhost:3000/vehiculos/find?ano=1997

###

GET http://localhost:3000/vehiculos/find?marca=Acura&ano=2013

###

GET http://localhost:3000/vehiculos/find?marca=Acura&ano=1997

###

GET http://localhost:3000/vehiculos/find?marca=Acuri&ano=1997