GET http://localhost:3000/api/events-login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGQ4ODA5ZjVjNThmMTczNDM0ZGZiZCIsInVzZXJuYW1lIjoiTWNMb3ZpbiIsImlhdCI6MTYyODI3Njc1NSwiZXhwIjoxNjI4ODgxNTU1fQ.He7RcVooUV1nmwzMLXlpNCEfbgMo9G7sE5B7YC0nGI0

###

GET http://localhost:3000/api/events-login?limit=5&skip=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGQ4ODA5ZjVjNThmMTczNDM0ZGZiZCIsInVzZXJuYW1lIjoiTWNMb3ZpbiIsImlhdCI6MTYyODI3Njc1NSwiZXhwIjoxNjI4ODgxNTU1fQ.He7RcVooUV1nmwzMLXlpNCEfbgMo9G7sE5B7YC0nGI0