GET http://localhost:3000/api/events-login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMDc2OWQwNWQ5NDM1MTc3Y2ZiODBmZCIsInVzZXJuYW1lIjoiTWNMb3ZpbiIsImlhdCI6MTYyNzg3NTgwMiwiZXhwIjoxNjI4NDgwNjAyfQ.FNUPWqXx23ihIIW528B20F4rcZB2iGcWedv_kdG0-JE

###

GET http://localhost:3000/api/events-login?limit=5&skip=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMDc2OWQwNWQ5NDM1MTc3Y2ZiODBmZCIsInVzZXJuYW1lIjoiTWNMb3ZpbiIsImlhdCI6MTYyNzg3NTgwMiwiZXhwIjoxNjI4NDgwNjAyfQ.FNUPWqXx23ihIIW528B20F4rcZB2iGcWedv_kdG0-JE