GET http://localhost:3000/api/events-login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGM5MjhiM2VjODNiMjMxNDlhYTVmMyIsInVzZXJuYW1lIjoiTWNMb3ZpbiIsImlhdCI6MTYyODIxMzkxMywiZXhwIjoxNjI4ODE4NzEzfQ.SlRUBxA9_XxE4_dHC5GMaLxlMZvGXA1zK22i2_IQ-Ys

###

GET http://localhost:3000/api/events-login?limit=5&skip=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGM5MjhiM2VjODNiMjMxNDlhYTVmMyIsInVzZXJuYW1lIjoiTWNMb3ZpbiIsImlhdCI6MTYyODIxMzkxMywiZXhwIjoxNjI4ODE4NzEzfQ.SlRUBxA9_XxE4_dHC5GMaLxlMZvGXA1zK22i2_IQ-Ys