POST http://localhost:3000/api/events-login
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGQ4ODA5ZjVjNThmMTczNDM0ZGZiZCIsInVzZXJuYW1lIjoiTWNMb3ZpbiIsImlhdCI6MTYyODI3Njc1NSwiZXhwIjoxNjI4ODgxNTU1fQ.He7RcVooUV1nmwzMLXlpNCEfbgMo9G7sE5B7YC0nGI0

{
    "title" : "FIESTA NACIONAL DE LA MANDARINA",
    "description" : "Esta fiesta rinde tributo a los productores locales y a todos aquellos que aportan su trabajo para el cultivo de la mandarina",
    "dateList" : ["2022-05-12T22:44:33.081+00:00", "2022-05-11T22:44:33.081+00:00", "2022-05-10T22:44:33.081+00:00"],
    "place" : "Chumbicha - Catamarca",
    "outstanding" : true,
    "image" : "http://#"
}

###

POST http://localhost:3000/api/events-login
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGQ4ODA5ZjVjNThmMTczNDM0ZGZiZCIsInVzZXJuYW1lIjoiTWNMb3ZpbiIsImlhdCI6MTYyODI3Njc1NSwiZXhwIjoxNjI4ODgxNTU1fQ.He7RcVooUV1nmwzMLXlpNCEfbgMo9G7sE5B7YC0nGI0

{
    "title" : "FORTNITE RIFT TOUR",
    "description" : "Concierto digital de la cantante Ariana Grande",
    "dateList" : ["2021-08-06T22:44:33.081+00:00", "2021-08-08T22:44:33.081+00:00", "2021-08-07T22:44:33.081+00:00"],
    "place" : "Dentro del videojuego Fotnite",
    "outstanding" : true,
    "image" : "http://#"
}

###

POST http://localhost:3000/api/events-login
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGQ4ODA5ZjVjNThmMTczNDM0ZGZiZCIsInVzZXJuYW1lIjoiTWNMb3ZpbiIsImlhdCI6MTYyODI3Njc1NSwiZXhwIjoxNjI4ODgxNTU1fQ.He7RcVooUV1nmwzMLXlpNCEfbgMo9G7sE5B7YC0nGI0

{
    "title" : "EVENTO 12",
    "description" : "Su descripción",
    "dateList" : ["2022-06-20T22:44:33.081+00:00", "2022-06-19T22:44:33.081+00:00"],
    "place" : "Su ubicación",
    "outstanding" : false,
    "image" : "http://#"
}

